### ISSUE TITLE
gateway example fails

### ISSUE THREAD

**Issue by phoenix24** [noisysockets/noisysockets#5] opened 2024-05-13 11:07 UTC
I've been getting the following error while trying to execute `examples/gateway`.  Do advice how to best go about it., or if there's something wrong or should execute otherwise.

```
➜  examples git:(main)  go run gateway/main.go
2024/05/13 16:30:05 github.com/testcontainers/testcontainers-go - Connected to docker: 
  Server Version: 26.0.0
  API Version: 1.45
  Operating System: Docker Desktop
  Total Memory: 7940 MB
  Resolved Docker Host: unix:///var/run/docker.sock
  Resolved Docker Socket Path: /var/run/docker.sock
  Test SessionID: 5be1e791a895b8f9fea0bc9926d4eb9baff33952d6d958b35334e091c0dd520f
  Test ProcessID: 25388bee-d0b0-4cd3-9354-e422363a534b
2024/05/13 16:30:05 🐳 Creating container for image testcontainers/ryuk:0.7.0
2024/05/13 16:30:05 ✅ Container created: 00e0e3071695
2024/05/13 16:30:05 🐳 Starting container: 00e0e3071695
2024/05/13 16:30:05 ✅ Container started: 00e0e3071695
2024/05/13 16:30:05 🚧 Waiting for container id 00e0e3071695 image: testcontainers/ryuk:0.7.0. Waiting for: &{Port:8080/tcp timeout:<nil> PollInterval:100ms}
2024/05/13 16:30:05 🔔 Container is ready: 00e0e3071695
2024/05/13 16:30:05 🐳 Creating container for image ghcr.io/noisysockets/gateway:v0.1.0
2024/05/13 16:30:05 ✅ Container created: 18bd2bfe8800
2024/05/13 16:30:05 🐳 Starting container: 18bd2bfe8800
2024/05/13 16:30:05 ✅ Container started: 18bd2bfe8800
2024/05/13 16:30:05 🚧 Waiting for container id 18bd2bfe8800 image: ghcr.io/noisysockets/gateway:v0.1.0. Waiting for: &{Port:53 timeout:<nil> PollInterval:100ms}
2024/05/13 16:30:06 🔔 Container is ready: 18bd2bfe8800
2024/05/13 16:34:20 ERROR Failed to make request error="Get \"https://icanhazip.com\": connect tcp 104.16.185.241:443: operation timed out"
exit status 1```

**Comment by dpeckett** [comment] 2024-05-13 11:29
Hmm this is very interesting, it suggests that something is wrong with the gateway container. If you replace `slog.Default()` in the example with `slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug}))` you should get some detailed debug logs (but atm this won't include the test container logs).

What platform/os are you using?

**Comment by dpeckett** [comment] 2024-05-13 11:38
Can you pull the latest commit on the `main` branch, and run the following commands from the root directory, this will give some more detailed information about whats going on.

```
docker run --rm -d --name=gateway \
 --cap-add NET_ADMIN \
 --sysctl net.ipv4.ip_forward=1 \
 --sysctl net.ipv4.conf.all.src_valid_mark=1 \
 -v /dev/net/tun:/dev/net/tun \
 -v $(pwd)/tests/testdata/wg0.conf:/etc/wireguard/wg0.conf:ro \
 ghcr.io/noisysockets/gateway:v0.1.0

docker logs gateway

docker rm -f gateway
```

**Comment by phoenix24** [comment] 2024-05-13 15:01
I think the issue is missing `wg-quick` - 

```➜  examples git:(main) ✗ docker logs gateway
Creating WireGuard Interface ...
/usr/bin/wg-quick: line 50: read: read error: 0: Is a directory
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip link set mtu 65455 up dev wg0
Starting dnsmasq DNS forwarder ...```

**Comment by phoenix24** [comment] 2024-05-13 15:02
please find debug logs from `example/gateway` below - 

```➜  examples git:(main) ✗ go run gateway/main.go
2024/05/13 20:19:30 github.com/testcontainers/testcontainers-go - Connected to docker: 
  Server Version: 26.0.0
  API Version: 1.45
  Operating System: Docker Desktop
  Total Memory: 7940 MB
  Resolved Docker Host: unix:///var/run/docker.sock
  Resolved Docker Socket Path: /var/run/docker.sock
  Test SessionID: f09a3b03826ebe3993df97e53412d9a152a737fe57be90467d355ba5f9e285f1
  Test ProcessID: 17aedd1f-5bba-4f38-9d9e-42e7e81df48b
2024/05/13 20:19:30 🐳 Creating container for image testcontainers/ryuk:0.7.0
2024/05/13 20:19:30 ✅ Container created: 2e6d1e21a3f9
2024/05/13 20:19:30 🐳 Starting container: 2e6d1e21a3f9
2024/05/13 20:19:30 ✅ Container started: 2e6d1e21a3f9
2024/05/13 20:19:30 🚧 Waiting for container id 2e6d1e21a3f9 image: testcontainers/ryuk:0.7.0. Waiting for: &{Port:8080/tcp timeout:<nil> PollInterval:100ms}
2024/05/13 20:19:30 🔔 Container is ready: 2e6d1e21a3f9
2024/05/13 20:19:30 Failed to get image auth for ghcr.io. Setting empty credentials for the image: ghcr.io/noisysockets/gateway:v0.1.0. Error is:credentials not found in native keychain
2024/05/13 20:20:07 🐳 Creating container for image ghcr.io/noisysockets/gateway:v0.1.0
2024/05/13 20:20:07 ✅ Container created: a4cdea2cdac4
2024/05/13 20:20:07 🐳 Starting container: a4cdea2cdac4
2024/05/13 20:20:07 ✅ Container started: a4cdea2cdac4
2024/05/13 20:20:07 🚧 Waiting for container id a4cdea2cdac4 image: ghcr.io/noisysockets/gateway:v0.1.0. Waiting for: &{Port:53 timeout:<nil> PollInterval:100ms}
2024/05/13 20:20:07 🔔 Container is ready: a4cdea2cdac4
2024/05/13 20:20:07 DEBUG Adding local address id=zbCx…iJQw address=10.0.0.2
2024/05/13 20:20:07 DEBUG Routine: encryption worker - started id=zbCx…iJQw id=5
2024/05/13 20:20:07 DEBUG Routine: encryption worker - started id=zbCx…iJQw id=1
2024/05/13 20:20:07 DEBUG Routine: encryption worker - started id=zbCx…iJQw id=3
2024/05/13 20:20:07 DEBUG Routine: decryption worker - started id=zbCx…iJQw id=1
2024/05/13 20:20:07 DEBUG Routine: decryption worker - started id=zbCx…iJQw id=3
2024/05/13 20:20:07 DEBUG Adding peer id=zbCx…iJQw name=gateway peer=wgTX…78H0
2024/05/13 20:20:07 DEBUG Routine: handshake worker - started id=zbCx…iJQw id=1
2024/05/13 20:20:07 DEBUG Routine: encryption worker - started id=zbCx…iJQw id=2
2024/05/13 20:20:07 DEBUG Routine: encryption worker - started id=zbCx…iJQw id=7
2024/05/13 20:20:07 DEBUG Routine: decryption worker - started id=zbCx…iJQw id=2
2024/05/13 20:20:07 DEBUG Routine: decryption worker - started id=zbCx…iJQw id=5
2024/05/13 20:20:07 DEBUG Routine: handshake worker - started id=zbCx…iJQw id=3
2024/05/13 20:20:07 DEBUG Routine: encryption worker - started id=zbCx…iJQw id=4
2024/05/13 20:20:07 DEBUG Routine: handshake worker - started id=zbCx…iJQw id=5
2024/05/13 20:20:07 DEBUG Routine: handshake worker - started id=zbCx…iJQw id=2
2024/05/13 20:20:07 DEBUG Routine: encryption worker - started id=zbCx…iJQw id=6
2024/05/13 20:20:07 DEBUG Routine: decryption worker - started id=zbCx…iJQw id=6
2024/05/13 20:20:07 DEBUG Routine: handshake worker - started id=zbCx…iJQw id=6
2024/05/13 20:20:07 DEBUG Routine: decryption worker - started id=zbCx…iJQw id=8
2024/05/13 20:20:07 DEBUG Routine: handshake worker - started id=zbCx…iJQw id=8
2024/05/13 20:20:07 DEBUG Routine: handshake worker - started id=zbCx…iJQw id=4
2024/05/13 20:20:07 DEBUG Routine: decryption worker - started id=zbCx…iJQw id=4
2024/05/13 20:20:07 DEBUG Routine: decryption worker - started id=zbCx…iJQw id=7
2024/05/13 20:20:07 DEBUG Adding address to routing table id=zbCx…iJQw peer=gateway address=10.0.0.1
2024/05/13 20:20:07 DEBUG Adding interval to routing table id=zbCx…iJQw peer=gateway prefix=10.0.0.1/32
2024/05/13 20:20:07 DEBUG Routine: handshake worker - started id=zbCx…iJQw id=7
2024/05/13 20:20:07 DEBUG Routine: encryption worker - started id=zbCx…iJQw id=8
2024/05/13 20:20:07 DEBUG Routine: Source reader - started id=zbCx…iJQw
2024/05/13 20:20:07 DEBUG Starting id=zbCx…iJQw peer=peer(wgTX…78H0)
2024/05/13 20:20:07 DEBUG Routine: sequential receiver - started id=zbCx…iJQw peer=peer(wgTX…78H0)
2024/05/13 20:20:07 DEBUG Sending keepalive packet id=zbCx…iJQw peer=peer(wgTX…78H0)
2024/05/13 20:20:07 DEBUG Adding route id=zbCx…iJQw destination=0.0.0.0/0 via=gateway
2024/05/13 20:20:07 DEBUG Adding address to routing table id=zbCx…iJQw peer=gateway address=10.0.0.1
2024/05/13 20:20:07 DEBUG Adding prefix to routing table id=zbCx…iJQw peer=gateway prefix=0.0.0.0/0
2024/05/13 20:20:07 DEBUG Adding interval to routing table id=zbCx…iJQw peer=gateway prefix=0.0.0.0/0
2024/05/13 20:20:07 DEBUG Routine: sequential sender - started id=zbCx…iJQw peer=peer(wgTX…78H0)
2024/05/13 20:20:07 DEBUG Bringing transport up id=zbCx…iJQw
2024/05/13 20:20:07 DEBUG UDP bind has been updated id=zbCx…iJQw
2024/05/13 20:20:07 DEBUG Sending handshake initiation id=zbCx…iJQw peer=peer(wgTX…78H0)
2024/05/13 20:20:07 DEBUG Routine: receive incoming - started id=zbCx…iJQw recvName=v4
2024/05/13 20:20:07 DEBUG Routine: receive incoming - started id=zbCx…iJQw recvName=v6
2024/05/13 20:20:07 DEBUG Interface state change requested id=zbCx…iJQw old=down want=up now=up
2024/05/13 20:20:07 DEBUG Dialing id=zbCx…iJQw network=tcp address=icanhazip.com:443
2024/05/13 20:20:07 DEBUG Looking up host id=zbCx…iJQw host=icanhazip.com
2024/05/13 20:20:07 DEBUG Trimmed search domains id=zbCx…iJQw host=icanhazip.com host=icanhazip.com.
2024/05/13 20:20:07 DEBUG Dialing id=zbCx…iJQw network=udp address=10.0.0.1:53
2024/05/13 20:20:07 DEBUG Looking up host id=zbCx…iJQw host=10.0.0.1
2024/05/13 20:20:07 DEBUG Host is an IP address id=zbCx…iJQw host=10.0.0.1
2024/05/13 20:20:07 DEBUG Received outbound packet from netstack id=zbCx…iJQw packetHash=16977166508171306347
2024/05/13 20:20:07 DEBUG Processing netstack packet id=zbCx…iJQw packetHash=16977166508171306347
2024/05/13 20:20:07 DEBUG Sending packet to peer id=zbCx…iJQw address=10.0.0.1 destination=wgTX…78H0
2024/05/13 20:20:07 DEBUG Received handshake response id=zbCx…iJQw id=1 from=127.0.0.1:52840 peer=peer(wgTX…78H0)
2024/05/13 20:20:08 DEBUG Received packet from peer id=zbCx…iJQw source=wgTX…78H0
2024/05/13 20:20:08 DEBUG Injecting inbound packet into netstack id=zbCx…iJQw
2024/05/13 20:20:08 DEBUG Dialing id=zbCx…iJQw network=udp address=104.16.185.241:9
2024/05/13 20:20:08 DEBUG Looking up host id=zbCx…iJQw host=104.16.185.241
2024/05/13 20:20:08 DEBUG Host is an IP address id=zbCx…iJQw host=104.16.185.241
2024/05/13 20:20:08 DEBUG Dialing id=zbCx…iJQw network=udp address=104.16.184.241:9
2024/05/13 20:20:08 DEBUG Looking up host id=zbCx…iJQw host=104.16.184.241
2024/05/13 20:20:08 DEBUG Host is an IP address id=zbCx…iJQw host=104.16.184.241
2024/05/13 20:20:08 DEBUG Host is a DNS name id=zbCx…iJQw host=icanhazip.com
2024/05/13 20:20:08 DEBUG Dialing id=zbCx…iJQw network=udp address=104.16.185.241:9
2024/05/13 20:20:08 DEBUG Looking up host id=zbCx…iJQw host=104.16.185.241
2024/05/13 20:20:08 DEBUG Host is an IP address id=zbCx…iJQw host=104.16.185.241
2024/05/13 20:20:08 DEBUG Dialing id=zbCx…iJQw network=udp address=104.16.184.241:9
2024/05/13 20:20:08 DEBUG Looking up host id=zbCx…iJQw host=104.16.184.241
2024/05/13 20:20:08 DEBUG Host is an IP address id=zbCx…iJQw host=104.16.184.241
2024/05/13 20:20:08 DEBUG Received outbound packet from netstack id=zbCx…iJQw packetHash=16759175014025785908
2024/05/13 20:20:08 DEBUG Processing netstack packet id=zbCx…iJQw packetHash=16759175014025785908
2024/05/13 20:20:08 DEBUG Sending packet to peer id=zbCx…iJQw address=104.16.185.241 destination=wgTX…78H0
2024/05/13 20:20:08 DEBUG Received packet from peer id=zbCx…iJQw source=wgTX…78H0
2024/05/13 20:20:08 DEBUG Injecting inbound packet into netstack id=zbCx…iJQw
2024/05/13 20:20:09 DEBUG Received outbound packet from netstack id=zbCx…iJQw packetHash=8952447411385253551
2024/05/13 20:20:09 DEBUG Processing netstack packet id=zbCx…iJQw packetHash=8952447411385253551
2024/05/13 20:20:09 DEBUG Sending packet to peer id=zbCx…iJQw address=104.16.185.241 destination=wgTX…78H0
2024/05/13 20:20:09 DEBUG Received packet from peer id=zbCx…iJQw source=wgTX…78H0
2024/05/13 20:20:09 DEBUG Injecting inbound packet into netstack id=zbCx…iJQw
2024/05/13 20:20:09 DEBUG Received packet from peer id=zbCx…iJQw source=wgTX…78H0
2024/05/13 20:20:09 DEBUG Injecting inbound packet into netstack id=zbCx…iJQw
2024/05/13 20:20:11 DEBUG Received outbound packet from netstack id=zbCx…iJQw packetHash=5732960044832143203
2024/05/13 20:20:11 DEBUG Processing netstack packet id=zbCx…iJQw packetHash=5732960044832143203
2024/05/13 20:20:11 DEBUG Sending packet to peer id=zbCx…iJQw address=104.16.185.241 destination=wgTX…78H0
2024/05/13 20:20:11 DEBUG Received packet from peer id=zbCx…iJQw source=wgTX…78H0
2024/05/13 20:20:11 DEBUG Injecting inbound packet into netstack id=zbCx…iJQw
2024/05/13 20:20:11 DEBUG Received packet from peer id=zbCx…iJQw source=wgTX…78H0
2024/05/13 20:20:11 DEBUG Injecting inbound packet into netstack id=zbCx…iJQw
2024/05/13 20:20:15 DEBUG Received outbound packet from netstack id=zbCx…iJQw packetHash=5094898151740072204
2024/05/13 20:20:15 DEBUG Processing netstack packet id=zbCx…iJQw packetHash=5094898151740072204
2024/05/13 20:20:15 DEBUG Sending packet to peer id=zbCx…iJQw address=104.16.185.241 destination=wgTX…78H0
2024/05/13 20:20:15 DEBUG Received packet from peer id=zbCx…iJQw source=wgTX…78H0
2024/05/13 20:20:15 DEBUG Injecting inbound packet into netstack id=zbCx…iJQw
2024/05/13 20:20:15 DEBUG Received packet from peer id=zbCx…iJQw source=wgTX…78H0
2024/05/13 20:20:15 DEBUG Injecting inbound packet into netstack id=zbCx…iJQw
2024/05/13 20:20:23 DEBUG Received outbound packet from netstack id=zbCx…iJQw packetHash=12136159249062671824
2024/05/13 20:20:23 DEBUG Processing netstack packet id=zbCx…iJQw packetHash=12136159249062671824
2024/05/13 20:20:23 DEBUG Sending packet to peer id=zbCx…iJQw address=104.16.185.241 destination=wgTX…78H0
2024/05/13 20:20:23 DEBUG Received packet from peer id=zbCx…iJQw source=wgTX…78H0
2024/05/13 20:20:23 DEBUG Injecting inbound packet into netstack id=zbCx…iJQw
2024/05/13 20:20:23 DEBUG Received packet from peer id=zbCx…iJQw source=wgTX…78H0
2024/05/13 20:20:23 DEBUG Injecting inbound packet into netstack id=zbCx…iJQw
2024/05/13 20:20:33 DEBUG Sending keepalive packet id=zbCx…iJQw peer=peer(wgTX…78H0)
2024/05/13 20:20:39 DEBUG Received outbound packet from netstack id=zbCx…iJQw packetHash=15865763277801790109
2024/05/13 20:20:39 DEBUG Processing netstack packet id=zbCx…iJQw packetHash=15865763277801790109
2024/05/13 20:20:39 DEBUG Sending packet to peer id=zbCx…iJQw address=104.16.185.241 destination=wgTX…78H0
2024/05/13 20:20:39 DEBUG Received packet from peer id=zbCx…iJQw source=wgTX…78H0
2024/05/13 20:20:39 DEBUG Injecting inbound packet into netstack id=zbCx…iJQw
2024/05/13 20:20:39 DEBUG Received packet from peer id=zbCx…iJQw source=wgTX…78H0
2024/05/13 20:20:39 DEBUG Injecting inbound packet into netstack id=zbCx…iJQw
2024/05/13 20:20:49 DEBUG Sending keepalive packet id=zbCx…iJQw peer=peer(wgTX…78H0)
2024/05/13 20:21:11 DEBUG Received outbound packet from netstack id=zbCx…iJQw packetHash=14259933849337670277
2024/05/13 20:21:11 DEBUG Processing netstack packet id=zbCx…iJQw packetHash=14259933849337670277
2024/05/13 20:21:11 DEBUG Sending packet to peer id=zbCx…iJQw address=104.16.185.241 destination=wgTX…78H0
2024/05/13 20:21:11 DEBUG Received packet from peer id=zbCx…iJQw source=wgTX…78H0
2024/05/13 20:21:11 DEBUG Injecting inbound packet into netstack id=zbCx…iJQw
2024/05/13 20:21:11 DEBUG Received packet from peer id=zbCx…iJQw source=wgTX…78H0
2024/05/13 20:21:11 DEBUG Injecting inbound packet into netstack id=zbCx…iJQw
2024/05/13 20:21:21 DEBUG Sending keepalive packet id=zbCx…iJQw peer=peer(wgTX…78H0)
2024/05/13 20:21:46 DEBUG Sending keepalive packet id=zbCx…iJQw peer=peer(wgTX…78H0)
2024/05/13 20:22:11 DEBUG Sending keepalive packet id=zbCx…iJQw peer=peer(wgTX…78H0)
2024/05/13 20:22:11 DEBUG Sending handshake initiation id=zbCx…iJQw peer=peer(wgTX…78H0)
2024/05/13 20:22:11 DEBUG Received handshake response id=zbCx…iJQw id=3 from=127.0.0.1:52840 peer=peer(wgTX…78H0)
2024/05/13 20:22:11 DEBUG Sending keepalive packet id=zbCx…iJQw peer=peer(wgTX…78H0)
2024/05/13 20:22:15 DEBUG Received outbound packet from netstack id=zbCx…iJQw packetHash=7632502369941930829
2024/05/13 20:22:15 DEBUG Processing netstack packet id=zbCx…iJQw packetHash=7632502369941930829
2024/05/13 20:22:15 DEBUG Sending packet to peer id=zbCx…iJQw address=104.16.184.241 destination=wgTX…78H0
2024/05/13 20:22:15 DEBUG Received packet from peer id=zbCx…iJQw source=wgTX…78H0
2024/05/13 20:22:15 DEBUG Injecting inbound packet into netstack id=zbCx…iJQw
2024/05/13 20:22:16 DEBUG Received outbound packet from netstack id=zbCx…iJQw packetHash=1262813081688894161
2024/05/13 20:22:16 DEBUG Processing netstack packet id=zbCx…iJQw packetHash=1262813081688894161
2024/05/13 20:22:16 DEBUG Sending packet to peer id=zbCx…iJQw address=104.16.184.241 destination=wgTX…78H0
2024/05/13 20:22:16 DEBUG Received packet from peer id=zbCx…iJQw source=wgTX…78H0
2024/05/13 20:22:16 DEBUG Injecting inbound packet into netstack id=zbCx…iJQw
2024/05/13 20:22:16 DEBUG Received packet from peer id=zbCx…iJQw source=wgTX…78H0
2024/05/13 20:22:16 DEBUG Injecting inbound packet into netstack id=zbCx…iJQw
2024/05/13 20:22:18 DEBUG Received outbound packet from netstack id=zbCx…iJQw packetHash=802095773823505528
2024/05/13 20:22:18 DEBUG Processing netstack packet id=zbCx…iJQw packetHash=802095773823505528
2024/05/13 20:22:18 DEBUG Sending packet to peer id=zbCx…iJQw address=104.16.184.241 destination=wgTX…78H0
2024/05/13 20:22:18 DEBUG Received packet from peer id=zbCx…iJQw source=wgTX…78H0
2024/05/13 20:22:18 DEBUG Injecting inbound packet into netstack id=zbCx…iJQw
2024/05/13 20:22:18 DEBUG Received packet from peer id=zbCx…iJQw source=wgTX…78H0
2024/05/13 20:22:18 DEBUG Injecting inbound packet into netstack id=zbCx…iJQw
2024/05/13 20:22:22 DEBUG Received outbound packet from netstack id=zbCx…iJQw packetHash=11999394785050954623
2024/05/13 20:22:22 DEBUG Processing netstack packet id=zbCx…iJQw packetHash=11999394785050954623
2024/05/13 20:22:22 DEBUG Sending packet to peer id=zbCx…iJQw address=104.16.184.241 destination=wgTX…78H0
2024/05/13 20:22:22 DEBUG Received packet from peer id=zbCx…iJQw source=wgTX…78H0
2024/05/13 20:22:22 DEBUG Injecting inbound packet into netstack id=zbCx…iJQw
2024/05/13 20:22:22 DEBUG Received packet from peer id=zbCx…iJQw source=wgTX…78H0
2024/05/13 20:22:22 DEBUG Injecting inbound packet into netstack id=zbCx…iJQw
2024/05/13 20:22:30 DEBUG Received outbound packet from netstack id=zbCx…iJQw packetHash=13357557624671907306
2024/05/13 20:22:30 DEBUG Processing netstack packet id=zbCx…iJQw packetHash=13357557624671907306
2024/05/13 20:22:30 DEBUG Sending packet to peer id=zbCx…iJQw address=104.16.184.241 destination=wgTX…78H0
2024/05/13 20:22:30 DEBUG Received packet from peer id=zbCx…iJQw source=wgTX…78H0
2024/05/13 20:22:30 DEBUG Injecting inbound packet into netstack id=zbCx…iJQw
2024/05/13 20:22:30 DEBUG Received packet from peer id=zbCx…iJQw source=wgTX…78H0
2024/05/13 20:22:30 DEBUG Injecting inbound packet into netstack id=zbCx…iJQw
2024/05/13 20:22:40 DEBUG Sending keepalive packet id=zbCx…iJQw peer=peer(wgTX…78H0)
2024/05/13 20:22:46 DEBUG Received outbound packet from netstack id=zbCx…iJQw packetHash=2354095394501952307
2024/05/13 20:22:46 DEBUG Processing netstack packet id=zbCx…iJQw packetHash=2354095394501952307
2024/05/13 20:22:46 DEBUG Sending packet to peer id=zbCx…iJQw address=104.16.184.241 destination=wgTX…78H0
2024/05/13 20:22:46 DEBUG Received packet from peer id=zbCx…iJQw source=wgTX…78H0
2024/05/13 20:22:46 DEBUG Injecting inbound packet into netstack id=zbCx…iJQw
2024/05/13 20:22:46 DEBUG Received packet from peer id=zbCx…iJQw source=wgTX…78H0
2024/05/13 20:22:46 DEBUG Injecting inbound packet into netstack id=zbCx…iJQw
2024/05/13 20:22:56 DEBUG Sending keepalive packet id=zbCx…iJQw peer=peer(wgTX…78H0)
2024/05/13 20:23:18 DEBUG Received outbound packet from netstack id=zbCx…iJQw packetHash=4509831984392602909
2024/05/13 20:23:18 DEBUG Processing netstack packet id=zbCx…iJQw packetHash=4509831984392602909
2024/05/13 20:23:18 DEBUG Sending packet to peer id=zbCx…iJQw address=104.16.184.241 destination=wgTX…78H0
2024/05/13 20:23:18 DEBUG Received packet from peer id=zbCx…iJQw source=wgTX…78H0
2024/05/13 20:23:18 DEBUG Injecting inbound packet into netstack id=zbCx…iJQw
2024/05/13 20:23:18 DEBUG Received packet from peer id=zbCx…iJQw source=wgTX…78H0
2024/05/13 20:23:18 DEBUG Injecting inbound packet into netstack id=zbCx…iJQw
2024/05/13 20:23:28 DEBUG Sending keepalive packet id=zbCx…iJQw peer=peer(wgTX…78H0)
2024/05/13 20:23:53 DEBUG Sending keepalive packet id=zbCx…iJQw peer=peer(wgTX…78H0)
2024/05/13 20:24:18 DEBUG Sending keepalive packet id=zbCx…iJQw peer=peer(wgTX…78H0)
2024/05/13 20:24:18 DEBUG Sending handshake initiation id=zbCx…iJQw peer=peer(wgTX…78H0)
2024/05/13 20:24:18 DEBUG Received handshake response id=zbCx…iJQw id=5 from=127.0.0.1:52840 peer=peer(wgTX…78H0)
2024/05/13 20:24:18 DEBUG Sending keepalive packet id=zbCx…iJQw peer=peer(wgTX…78H0)
2024/05/13 20:24:22 ERROR Failed to make request error="Get \"https://icanhazip.com\": connect tcp 104.16.185.241:443: operation timed out"
exit status 1

**Comment by dpeckett** [comment] 2024-05-13 15:19
Yep the issue is definitely somewhere inside the gateway container.

Though that read error suggests an issue with bind mounting the `wg0.conf` which makes no sense. Maybe its an iptables / packet forwarding issue with Docker Desktop (is this mac or windows?). 

I'm planning on writing a kind of userspace, slirp inspired gateway node hopefully will fix this in the future.

**Comment by phoenix24** [comment] 2024-05-13 15:26
this is on mac osx, 14.4.1

**Comment by dpeckett** [comment] 2024-05-14 17:00
I've been able to recreate the issue, everything appears to come up but no packet forwarding occurs, looks like wireguard-go and Docker Desktop for Mac is going to need some further work, might be a TAP device issue or something.

**Comment by dpeckett** [comment] 2024-05-23 17:28
Fixed in: https://github.com/noisysockets/noisysockets/commit/4ba5b0ed16d644daaa7c1442650ec14602853be6 

No longer using a wireguard-go container but rather our own slirp-like userspace router.

**Closed by dpeckett** 2024-05-23 17:28 UTC
